[package]
name = "async-await-server"
version = "0.1.0"
authors = ["Sean <seanchen11235@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.1"
romio = "0.3.0-alpha.1"
file-lock = "1.1.20"
lru-cache = "0.1.1"

[dependencies.futures]
version = "0.3.0-alpha.10"
package = "futures-preview"